### ISSUE TITLE
Make turrets cheaper i beg you

### ISSUE THREAD

**Issue by kapzduke** [gorodmi/randomMindustry#19]
![image](https://user-images.githubusercontent.com/60543005/177652470-f578d0a6-1d28-4c52-8eee-4f8ec6d6096c.png)
![image](https://user-images.githubusercontent.com/60543005/177652503-30ecf66a-4e8b-4ec0-9964-f0e1e84bce4a.png)

**Comment by Mythril382** [comment]
issue solved(?)
